name: Deploy Dev
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2
      - run: pnpm install
      - run: pnpx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: pnpx vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
